[project]
name = "dads-finance-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.0"
dependencies = [
    "ollama>=0.4.7",
    "pydantic>=2.10.6",
]
